name: Cross-Repository Coordination
description: For changes affecting multiple repositories in the Loqa ecosystem
title: "[Cross-Repo]: "
labels: ["coordination", "cross-repo", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Cross-Repository Coordination Issue
        
        Use this template for changes that span multiple repositories in the Loqa ecosystem.
        This will automatically create tracking issues in affected repositories and enable
        status synchronization across the coordination effort.

  - type: dropdown
    id: change_type
    attributes:
      label: Change Type
      description: What type of coordinated change is this?
      options:
        - Protocol Change (loqa-proto → consumers)
        - Breaking Change (multiple repos)
        - Feature Rollout (coordinated deployment)
        - Security Update (all repos)
        - Bug Fix (cross-repo impact)
        - Performance Optimization (multi-service)
        - Documentation Update (cross-repo)
    validations:
      required: true

  - type: checkboxes
    id: affected_repos
    attributes:
      label: Affected Repositories
      description: Check all repositories that need changes
      options:
        - label: loqa-proto (gRPC protocol definitions)
        - label: loqa-hub (central orchestrator service)
        - label: loqa-relay (audio capture client)
        - label: loqa-skills (skill plugin system)
        - label: loqa-commander (Vue.js admin dashboard)
        - label: loqa (orchestration and documentation)
        - label: www-loqalabs-com (public website)
        - label: loqalabs-github-config (shared GitHub workflows)

  - type: textarea
    id: coordination_summary
    attributes:
      label: Coordination Summary
      description: Brief description of what needs to be coordinated
      placeholder: "Example: Update authentication protocol across all services to support JWT tokens"
    validations:
      required: true

  - type: textarea
    id: coordination_plan
    attributes:
      label: Detailed Coordination Plan
      description: Step-by-step plan with dependencies and sequence
      placeholder: |
        1. Update loqa-proto with new authentication messages
        2. Update loqa-hub to implement JWT validation
        3. Update loqa-relay to send JWT tokens
        4. Update loqa-skills to use new auth context
        5. Update loqa-commander to handle new auth flow
        6. Test end-to-end authentication
        7. Update documentation and deployment guides
      value: |
        ## Implementation Sequence
        1. [ ] 
        2. [ ] 
        3. [ ] 
        
        ## Dependencies
        - Repository A must be updated before Repository B
        - 
        
        ## Testing Strategy
        - 
        
        ## Rollback Plan
        - 
    validations:
      required: true

  - type: dropdown
    id: coordination_priority
    attributes:
      label: Coordination Priority
      description: How urgent is this coordination effort?
      options:
        - Low - can proceed independently with loose coordination
        - Medium - requires coordination but not blocking
        - High - requires tight coordination, may block other work
        - Critical - blocking critical functionality or security issue
    validations:
      required: true

  - type: dropdown
    id: breaking_change
    attributes:
      label: Breaking Change Impact
      description: Does this introduce breaking changes?
      options:
        - "No - fully backward compatible"
        - "Minor - deprecation warnings only"
        - "Major - requires coordinated updates"
        - "Critical - immediate action required"
    validations:
      required: true

  - type: textarea
    id: integration_testing
    attributes:
      label: Integration Testing Strategy
      description: How will cross-repository changes be tested together?
      placeholder: |
        - Unit tests in each repository
        - Integration tests with docker-compose
        - End-to-end testing with real voice pipeline
        - Performance testing under load
        - Backward compatibility testing
    validations:
      required: true

  - type: textarea
    id: deployment_strategy
    attributes:
      label: Deployment Strategy
      description: How will the coordinated changes be deployed?
      placeholder: |
        - Feature flags for gradual rollout
        - Blue-green deployment strategy
        - Rolling updates with health checks
        - Rollback procedures if issues occur
    validations:
      required: true

  - type: input
    id: target_milestone
    attributes:
      label: Target Milestone/Version
      description: When should this coordination effort be completed?
      placeholder: "v1.2.0, Q4 2024, etc."

  - type: textarea
    id: communication_plan
    attributes:
      label: Communication Plan
      description: How will progress and blockers be communicated?
      placeholder: |
        - Daily standups for high priority items
        - Weekly progress updates in coordination issue
        - Slack notifications for blockers
        - Email updates for milestone completion

  - type: checkboxes
    id: coordination_checklist
    attributes:
      label: Coordination Checklist
      description: Track overall progress (will be auto-updated)
      options:
        - label: Child issues created in affected repositories
        - label: Implementation plan reviewed and approved
        - label: Feature branches created in all affected repos
        - label: Development work completed in all repos
        - label: Unit tests passing in all repositories
        - label: Integration tests passing across repositories
        - label: Code reviews completed in all repositories
        - label: Documentation updated in all affected repos
        - label: Deployment plan reviewed and approved
        - label: Production deployment completed
        - label: Post-deployment verification completed
        - label: Coordination effort retrospective completed

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information, links, or context
      placeholder: |
        - Related issues or PRs
        - External dependencies
        - Risk factors
        - Success criteria

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/loqalabs/loqa/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true