name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["template-feature", "priority-medium"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! This template helps us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: Currently, users cannot...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution in detail.
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete? List specific requirements.
      placeholder: |
        - [ ] Users can...
        - [ ] The system should...
        - [ ] Error handling for...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this feature?
      options:
        - priority-low
        - priority-medium
        - priority-high
        - priority-critical
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, examples, or other relevant information.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true