#!/bin/bash
#
# Script to add AGPLv3 license headers to all source files
#

# Go license header
GO_HEADER="/*
 * This file is part of Loqa (https://github.com/loqalabs/loqa).
 * Copyright (C) 2025 Loqa Labs
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

"

# Shell/Python license header  
SHELL_HEADER="# This file is part of Loqa (https://github.com/loqalabs/loqa).
# Copyright (C) 2025 Loqa Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"

# Function to add license header to Go files
add_go_header() {
    local file="$1"
    
    # Skip if already has license header
    if grep -q "GNU Affero General Public License" "$file"; then
        echo "  Skipping $file (already has license header)"
        return
    fi
    
    # Skip generated protobuf files
    if grep -q "Code generated by protoc-gen-go. DO NOT EDIT." "$file"; then
        echo "  Skipping $file (generated protobuf file)"
        return
    fi
    
    # Create temporary file with license header + original content
    {
        echo -n "$GO_HEADER"
        cat "$file"
    } > "${file}.tmp"
    
    mv "${file}.tmp" "$file"
    echo "  Added header to $file"
}

# Function to add license header to shell/python files
add_shell_header() {
    local file="$1"
    
    # Skip if already has license header
    if grep -q "GNU Affero General Public License" "$file"; then
        echo "  Skipping $file (already has license header)"
        return
    fi
    
    # Handle shebang line
    if head -n1 "$file" | grep -q "^#!"; then
        # File has shebang - preserve it
        {
            head -n1 "$file"
            echo ""
            echo -n "$SHELL_HEADER"
            tail -n +2 "$file"
        } > "${file}.tmp"
    else
        # No shebang - just add header
        {
            echo -n "$SHELL_HEADER"
            cat "$file"
        } > "${file}.tmp"
    fi
    
    mv "${file}.tmp" "$file"
    echo "  Added header to $file"
}

# Process each repository
for repo_path in /Users/anna/Projects/loqalabs/loqa-*; do
    repo_name=$(basename "$repo_path")
    echo "Processing $repo_name..."
    
    cd "$repo_path" || continue
    
    # Add headers to Go files
    find . -name "*.go" -type f | while read -r file; do
        add_go_header "$file"
    done
    
    # Add headers to shell files
    find . -name "*.sh" -type f | while read -r file; do
        add_shell_header "$file"
    done
    
    # Add headers to Python files
    find . -name "*.py" -type f | while read -r file; do
        add_shell_header "$file"
    done
    
    echo "Completed $repo_name"
    echo ""
done

echo "License header addition complete!"