#!/bin/bash

# Install Smart Git Detection for Loqa Development
# This makes the smart git functionality available to all developers

set -e

echo "🔧 Installing Smart Git Detection for Loqa..."
echo

# Get the script directory (loqa/tools/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOQA_ROOT="$(dirname "$SCRIPT_DIR")"
MCP_DIR="$LOQA_ROOT/project/loqa-assistant-mcp"

echo "📂 Loqa root: $LOQA_ROOT"
echo "📂 MCP project: $MCP_DIR"
echo

# Check if MCP directory exists
if [[ ! -d "$MCP_DIR" ]]; then
    echo "❌ Error: MCP directory not found at $MCP_DIR"
    exit 1
fi

# Build the MCP project if needed
echo "🔨 Building smart git utilities..."
cd "$MCP_DIR"

if [[ ! -d "node_modules" ]]; then
    echo "📦 Installing dependencies..."
    npm install
fi

echo "🏗️  Building TypeScript..."
npm run build

# Check if build succeeded
if [[ ! -f "dist/cli/smart-git.js" ]]; then
    echo "❌ Error: Build failed - smart-git.js not found"
    exit 1
fi

# Create a global wrapper script in loqa/tools/
WRAPPER_SCRIPT="$LOQA_ROOT/tools/smart-git"

echo "📝 Creating global wrapper at $WRAPPER_SCRIPT"

cat > "$WRAPPER_SCRIPT" << EOF
#!/bin/bash
# Smart Git Detection for Loqa - Global Wrapper
# Auto-generated by install-smart-git.sh

# Path to the smart git CLI
SMART_GIT_CLI="$MCP_DIR/dist/cli/smart-git.js"

# Check if CLI exists
if [[ ! -f "\$SMART_GIT_CLI" ]]; then
    echo "❌ Error: Smart git CLI not found. Run tools/install-smart-git.sh to reinstall."
    exit 1
fi

# Execute the smart git command
exec node "\$SMART_GIT_CLI" "\$@"
EOF

# Make the wrapper executable
chmod +x "$WRAPPER_SCRIPT"

# Test the installation
echo "🧪 Testing installation..."
if "$WRAPPER_SCRIPT" status >/dev/null 2>&1; then
    echo "✅ Smart git installed successfully!"
else
    echo "⚠️  Installation completed but test failed (you may not be in a git repo)"
fi

echo
echo "🚀 Usage:"
echo "   ./tools/smart-git status           # Smart git status"  
echo "   ./tools/smart-git branch feat-x    # Create feature branch"
echo "   ./tools/smart-git commit \"msg\"     # Smart commit"
echo "   ./tools/smart-git <any-git-cmd>    # Any git command from repo root"
echo
echo "💡 Add this to your shell profile for global access:"
echo "   export PATH=\"$LOQA_ROOT/tools:\$PATH\""
echo "   # Then use: smart-git status"
echo
echo "📚 For Claude Code users: MCP server provides enhanced AI integration"
echo "   Run from VS Code with Claude Code extension for AI-powered workflows"

# Optional: Add to PATH for this session
if [[ ":$PATH:" != *":$LOQA_ROOT/tools:"* ]]; then
    echo
    echo "🔗 Adding to PATH for this session..."
    export PATH="$LOQA_ROOT/tools:$PATH"
    echo "   You can now use: smart-git <command>"
fi