name: Documentation CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    name: Validate Documentation
    uses: loqalabs/.github/.github/workflows/js-validate-docs.yml@main
    with:
      node-version: '20'

  spell-check:
    name: Spell Check
    uses: loqalabs/.github/.github/workflows/js-spell-check.yml@main
    with:
      node-version: '20'

  build-site:
    name: Build Documentation Site
    uses: loqalabs/.github/.github/workflows/js-build-site.yml@main
    needs: [validate, spell-check]
    with:
      node-version: '20'

  deploy:
    name: Deploy to GitHub Pages
    needs: [validate, build-site]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: loqalabs/.github/.github/workflows/js-deploy-pages.yml@main
    with:
      node-version: '20'
      cname: '' # Set to custom domain if needed