name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    name: Validate Documentation
    uses: loqalabs/.github/.github/workflows/validate-docs.yml@main
    with:
      node-version: '20'

  check-docs-changes:
    name: Check for Documentation Changes
    runs-on: ubuntu-latest
    outputs:
      docs-changed: ${{ steps.changes.outputs.docs }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            docs:
              - '**/*.md'
              - '**/*.rst'
              - '**/*.txt'
              - 'docs/**'

  spell-check:
    name: Spell Check
    needs: check-docs-changes
    if: needs.check-docs-changes.outputs.docs-changed == 'true'
    uses: loqalabs/.github/.github/workflows/spell-check-fast.yml@main

  build-site:
    name: Build Documentation Site
    uses: loqalabs/.github/.github/workflows/mkdocs-build-site.yml@main
    needs: [validate, spell-check]
    if: always() && needs.validate.result == 'success' && (needs.spell-check.result == 'success' || needs.spell-check.result == 'skipped')
    with:
      artifact-name: documentation-site

  deploy:
    name: Deploy to GitHub Pages
    needs: [validate, build-site]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: loqalabs/.github/.github/workflows/mkdocs-deploy-pages.yml@main