name: Security Scan

on:
  schedule:
    # Weekly security scan on Sundays at 4:00 AM UTC
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  security-mcp:
    name: MCP Server Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'javascript'
      node-version: '20'
      working-directory: 'project/loqa-assistant-mcp'
    secrets: inherit

  security-scripts:
    name: Shell Scripts Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'shell'
      working-directory: 'tools'
    secrets: inherit